# Logical Operators

In [ ]:
a = True
b = False

In [2]:
a & b

False

In [3]:
b & a

False

In [4]:
a & a

True

In [5]:
b & b

False

In [6]:
a | b

True

In [7]:
b | a

True

In [8]:
a | a

True

In [9]:
b | b

False

# Python Strings

In [1]:
x = "Ram is a good boy"

In [2]:
len(x) # inclusive of space

17

In [3]:
x[0] # indexing starts from 0

'R'

In [4]:
x[2:] # from index 2 to last index

'm is a good boy'

In [5]:
x[:2] # from index 0 to befor index 2

'Ra'

In [6]:
x[2:7] # from index 2 to before index 7

'm is '

In [7]:
x[-1] # last index

'y'

# Python Data Structures : Tuple,List,Dictionary,Set

In [14]:
## Variables store single value where as data structure s store multiple values

# tuples are immutable ie. cant be changed
tuple1 = (1,"a",True,23.0)
tuple1

(1, 'a', True, 23.0)

In [15]:
tuple1[0:3] # from index 0 to 2

(1, 'a', True)

In [35]:
tuple1[5] = 5 # immutability

TypeError: 'tuple' object does not support item assignment

In [17]:
# lists are mutable

list1 = [1,"a",23.0,"b",True]
list1

[1, 'a', 23.0, 'b', True]

In [19]:
list1[0] = "Hello" # mutability
list1

['Hello', 'a', 23.0, 'b', True]

In [20]:
list1.append("x")
list1

['Hello', 'a', 23.0, 'b', True, 'x']

In [21]:
list1.pop()

'x'

In [22]:
list1

['Hello', 'a', 23.0, 'b', True]

In [26]:
dict1 = {"mango":45,"apple":7,"orange":10,"banana":12}
dict1

{'mango': 45, 'apple': 7, 'orange': 10, 'banana': 12}

In [27]:
dict1.keys()

dict_keys(['mango', 'apple', 'orange', 'banana'])

In [28]:
dict1.values()

dict_values([45, 7, 10, 12])

In [30]:
dict1["mango"] = 100
dict1

{'mango': 100, 'apple': 7, 'orange': 10, 'banana': 12}

In [31]:
dict1["mango"]

100

In [32]:
# sets are unindexed and no duplicates

set1 = {1,"a",3.78}
set1

{1, 3.78, 'a'}

In [33]:
set1.add("Hello") # to add a single element
set1

{1, 3.78, 'Hello', 'a'}

In [34]:
set1.update([1,2,3]) # to add multiple elements
set1

{1, 2, 3, 3.78, 'Hello', 'a'}

# Flow control statements

**if else statement**

In [1]:
a =10
b = 20
if(b > a):
    print("b is greater than a")
else:
    print("b is not greater than a")

b is greater than a


**if else if else statement**

In [2]:
a = 10
b = 20
c = 30
if (a > b) & (a > c):
    print("a is greatest")
elif (b > a) & (b > c):
    print("b is greatest")
else:
    print("c is greatest")

c is greatest


In [4]:
# tuple with if
tuple1 = ("a","b","c")
if "a" in tuple1:
    print("a is present")

a is present


In [5]:
# list with if
list1 = [10,20,30,40,50]
if list1[0] == 10:
    list1[0] = 100
list1


[100, 20, 30, 40, 50]

In [6]:
# dictionary with if
dict1 = {"mango":10,"apple":20,"banana":30}
if dict1["mango"] == 10:
    dict1["mango"] = dict1["mango"] + 100
dict1

{'mango': 110, 'apple': 20, 'banana': 30}

**while loop**

In [7]:
i = 1
while (i <= 5):
    print(i)
    i = i + 1

1
2
3
4
5


In [8]:
# while with list
list1 = [1,2,3,4,5]
i = 0
while i < len(list1):
    list1[i] = list1[i] + 100
    i = i + 1
list1

[101, 102, 103, 104, 105]

**for loop**

In [9]:
# list with for
list1 = ["blue","green","red"]
for i in list1:
    print (i)

blue
green
red


In [10]:
color = ["green","yellow","pink"]
item = ["chair","book","phone"]
for i in color:
    for j in item:
        print(i,j)

green chair
green book
green phone
yellow chair
yellow book
yellow phone
pink chair
pink book
pink phone


# Python Functions 

In [11]:
def hello():
    print("Hello world")
hello()

Hello world


#  Python OOP

In [3]:
# class : general template
# object : specific instance of class
# first letter of the name of class is in capital letter
class Phone:
    def make_call(self):
        print("Making a phone call")
    def play_game(self):
        print("Play games")
        
p1 = Phone() # an instance of class Phone
p1.make_call()
p1.play_game()
    
    

Making a phone call
Play games


In [6]:
class Phone:
    def add_color(self,color):
        self.color = color
    def add_cost(self,cost):
        self.cost = cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(self):
        print("Making a phone call")
    def play_game(self):
        print("Play games")
    
p1 = Phone()
p1.add_color("blue")
p1.add_cost(2000)
p1.show_color()

'blue'

In [7]:
# inheritance
class Iphone(Phone):
    def cure_cancer(self):
        print("i can cure cancer")
ip1 = Iphone()
ip1.add_color("gray")
ip1.cure_cancer()

i can cure cancer


# Numpy Library in Python

In [11]:
# numerical python for numeric and scientific computation
import numpy as np

In [9]:
arr1 = np.array([10,20,30,40]) # single-dimensional array
arr1

array([10, 20, 30, 40])

In [10]:
arr2 = np.array([[10,20,30,40],[40,30,20,10]]) # multi-dimensional array
arr2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
type(arr2)

numpy.ndarray

In [15]:
arr3 = np.zeros((1,2)) # np.zeros(rows,cols)
arr3

array([[0., 0.]])

In [16]:
arr4 = np.full((2,2),10) # np.full((rows,cols),same number)
arr4

array([[10, 10],
       [10, 10]])

In [18]:
arr5 = np.arange(10,50,5) # np.arange(start no,end no exclusive the no,skip value)
arr5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
arr6 = np.random.randint(1,100,5) # np.random.randint(start no,end no,no of values)
arr6

array([11, 24, 19, 38, 74])

In [20]:
arr7 = np.array([[1,2,3],[4,5,6]])
arr7.shape

(2, 3)

In [21]:
arr7.shape = (3,2)
arr7

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
n1 = np.array([10,20])
n2 = np.array([30,40])
np.sum([n1,n2])

100

In [24]:
np.sum([n1,n2],axis = 0) # vertical sum

array([40, 60])

In [25]:
np.sum([n1,n2],axis = 1) # horizontal sum

array([30, 70])

**joining NumPy arrays**

In [26]:
np.vstack((n1,n2)) # vertical stack or row-wise

array([[10, 20],
       [30, 40]])

In [27]:
np.hstack((n1,n2)) # head stack or column-wise

array([10, 20, 30, 40])

In [28]:
np.column_stack((n1,n2))

array([[10, 30],
       [20, 40]])

# Pandas Library in Python

In [33]:
# Panel Data for data manipulation and data analysis
# consists of single (series object) and multi-dimensional (data-frame) data structures for data manipulation
import pandas as pd

**Series is 1-D labeled array**

In [36]:
s1 = pd.Series([1,2,3,4,5]) 
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [37]:
type(s1)

pandas.core.series.Series

In [38]:
s1 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e']) # labels changed
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [39]:
pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5}) # series object from dictionary

a    1
b    2
c    3
d    4
e    5
dtype: int64

**Data-frame is 2-D labelled data-structure**

In [40]:
pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,45,59]})

Name  Marks
0   Bob     76
1   Sam     45
2  Anne     59

In [46]:
import pandas as pd
iris = pd.read_csv('Iris.csv')

In [44]:
iris.head() # by default first five 

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [47]:
iris.tail() # by default last five

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [48]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [49]:
iris.iloc[0:3,0:2] # rows index range,cols index range

Id  SepalLengthCm
0   1            5.1
1   2            4.9
2   3            4.7

In [50]:
iris.loc[0:3,("SepalLengthCm","PetalLengthCm")]

SepalLengthCm  PetalLengthCm
0            5.1            1.4
1            4.9            1.4
2            4.7            1.3
3            4.6            1.5

In [52]:
iris[iris['SepalLengthCm'] > 5 ] # to extract first iris and to define condition second iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
10    11            5.4           3.7            1.5           0.2   
14    15            5.8           4.0            1.2           0.2   
15    16            5.7           4.4            1.5           0.4   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
5       Iris-setosa  
10      Iris-setosa  
14      Iris-setosa  
15      Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[118 rows x 6 columns]